# ----------- CONFIGURABLE START -----------
title:            "2018 PACE NSC Program"
url:              https://pacensc.github.io # Site url, without a slash at the end.
signoff:          "PACE" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
theme: jekyll-swiss
theme_color: white

links: 
  - name:         Playoff Seeds
    url:          /playoff-seeds
    external:     false
  - name:         2018 Schedule
    url:          /schedules
    external:     false
  - name:         Team Directory
    url:          /team-directory
    external:     false
  - name:         NSC Social Media
    url:          /social-media
    external:     false
  - name:         NSC Rules
    url:          /rules
    external:     false
  - name:         2018 Cooper Awards
    url:          /cooper
    external:     false
  - name:         PACE Homepage
    url:          http://pace-nsc.org
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
markdown: kramdown
 
kramdown:
  toc_levels: 1..2
defaults:
  - values:
      layout: "default"

