# ----------- CONFIGURABLE START -----------
title:            "2019 PACE NSC"
url:              https://pacensc.github.io # Site url, without a slash at the end.
signoff:          "PACE" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
theme: jekyll-theme-minimal

links: 
#  - name:         Playoff Seeds
#    url:          /playoff-seeds
#    external:     false
  - name:         Schedule
    url:          /schedules
    external:     false
  - name:         Program
    url:          /program
    external:     false
  - name:         Rules
    url:          /rules
    external:     false
  - name:         Social Media
    url:          /social-media
    external:     false
  - name:         Cooper Awards
    url:          /cooper
    external:     false
  - name:         PACE Homepage
    url:          http://pace-nsc.org
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
markdown: kramdown
 
kramdown:
  toc_levels: 1..2
defaults:
  - values:
      layout: "default"

